changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{ts,tsx}"
  - "**/*.stories.{ts,tsx}"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
